### ISSUE TITLE
Unable to add tags / labels to new issues on this repository

### ISSUE THREAD

**Issue by dkd903** [hhroc/yellr-ios#11]

**Comment by thequbit** [comment]
Added task as label.  I think you should have permissions to create new tags ... if you still don't let me know and I'll look into it further.

**Comment by dkd903** [comment]
On the labels tab, I can just see labels. Unable to create any.

**Comment by thequbit** [comment]
Give it a try now.

**Comment by dkd903** [comment]
Works now.
