### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dkd903** [hhroc/yellr-ios#14]
I want to get localization out of the way so that we do end up reaching a point where the codebase needs major overhaul in order to incorporate Language support

**Comment by thequbit** [comment]
Is this closed with #17?  Or should it still be considered open?  This is just adding the hooks for localization, not "all the languages we'll support".

**Comment by dkd903** [comment]
The functionality is in. But the spanish language file needs to be updated.

**Comment by thequbit** [comment]
Let's close this one, and then please open a new ticket that states that the Spanish files are out of date.
