### ISSUE TITLE
Create scene for List of Local Posts

### ISSUE THREAD

**Issue by dkd903** [hhroc/yellr-ios#5]

**Comment by thequbit** [comment]
Local post items should display:
- upvote icon
- downvote icon
- upvote count
- downvote count
- any text in the post
- any image in the post

**Comment by thequbit** [comment]
Right now the action of clicking on the post doesn't do anything in the Android app.  I've been working on that.  It should work similarly to twitter, in that a scene should exist where the post can be seen.  We should truncate the text in the list so it's not too long, then then display all of it in the view post scene.

**Comment by dkd903** [comment]
I pushed an update today that displays all that information in the screens. The layout is off though, which I will fix soon.
![ios simulator screen shot may 30 2015 8 02 45 pm](https://cloud.githubusercontent.com/assets/233879/7899929/ec81e062-0706-11e5-8e37-f09ac6e97091.png)

**Comment by thequbit** [comment]
NICE!!!!

Perfect!

Take a look at the color's that are used in the android app for green (upvotes) and red (downvotes).

Green:
https://github.com/hhroc/yellr-android/blob/master/app/src/main/res/values/colors.xml#L15

Red:
https://github.com/hhroc/yellr-android/blob/master/app/src/main/res/values/colors.xml#L13

**Comment by thequbit** [comment]
Closed with #17
